name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code from the testing repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Checkout source code repository
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          repository: <hytechbarett>/<hytechbarett/gizmo>
          token: ${{ secrets.GITHUB_TOKEN }}
          path: source_code

      # Step 3: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.12.2"

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 5: Set up environment variables
      - name: Set up environment variables
        run: |
          echo "USERNAME_HYTECH=${{ secrets.USERNAME_HYTECH }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV

      # Step 6: Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run --headless --no-exit
